services:
  simatic_server_socket:
    class: Pjpl\SimaticServerBundle\DependencyInjection\SimaticServerSocket
    arguments: [%simatic_server_ip%, %simatic_server_port%, %simatic_server_timeout_sek%]
